[package]
name = "streaming-qcow2-writer"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
byteorder = "1.4"
serde = { version = "*", features = ["derive"] }
serde_json = "*"

[target.'cfg(unix)'.dependencies]
nix = "*"
